"""Add funding fields to Shift and ShiftRoster models

Revision ID: 799316497651
Revises: 9abdbcb1089f
Create Date: 2026-01-14 01:04:23.326417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '799316497651'
down_revision = '9abdbcb1089f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_funded', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('funded_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('funding_transaction_id', sa.String(length=100), nullable=True))

    with op.batch_alter_table('shifts_roster', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payout_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('is_paid', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('paid_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shifts_roster', schema=None) as batch_op:
        batch_op.drop_column('paid_at')
        batch_op.drop_column('is_paid')
        batch_op.drop_column('payout_amount')

    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.drop_column('funding_transaction_id')
        batch_op.drop_column('funded_amount')
        batch_op.drop_column('is_funded')

    # ### end Alembic commands ###
