"""add description field to shifts table

Revision ID: 9abdbcb1089f
Revises: aac224d0ffdc
Create Date: 2026-01-13 19:58:08.239438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9abdbcb1089f'
down_revision = 'aac224d0ffdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shifts', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
